# -*- coding: utf-8 -*-
"""skin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19V9x94MOBpyLpVqxIUdcVqU1QtWi2vA-
"""

!pip install ultralytics
!pip install opencv-python
!pip install roboflow

from ultralytics import YOLO
import cv2
import torch
import matplotlib.pyplot as plt
from roboflow import Roboflow

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.applications import EfficientNetB0
import cv2
import numpy as np
import os
from roboflow import Roboflow
import matplotlib.pyplot as plt

rf = Roboflow(api_key="8zRMqJEoelKszap5KEO2")
project = rf.workspace("workshop-yg2yt").project("skin-3n2jd")
dataset = project.version(1).download("yolov8")

model = YOLO("yolov8n.pt")  # Load YOLOv8 nano model (use yolov8s.pt for small, yolov8m.pt for medium)

# Train the model
model.train(data="/content/Skin-1/data.yaml", epochs=50, imgsz=640, batch=8)

metrics = model.val()
print(metrics)

results = model("/content/Skin-1/test/images/image_214_jpg.rf.dee6c8774cc66a6b734afe14429b9681.jpg")
results[0].show()  # Display the detected pests

model.save("skin.h5")

model.save("skin.pt")

